#!/bin/bash
#
# kerneloops
#
# chkconfig:   345 90 88
# description: A tool that collects and submits kernel crash \
# signatures to the kerneloops.org website for use by the Linux \
# kernel developers.
# processname: kerneloops
# config:      /etc/kerneloops.conf
#
### BEGIN INIT INFO
# Provides: kerneloops
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Required-Start: $local_fs $remote_fs $named $network $time $syslog
# Required-Stop: $local_fs $remote_fs $syslog
# Short-Description: Tool to automatically collect and submit kernel crash signatures
# Description: A tool that collects and submits kernel crash
#   signatures to the kerneloops.org website for use by the Linux
#   kernel developers.
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions


exec="/usr/sbin/kerneloops"
prog=$(basename $exec)
pidfile=/var/run/$prog.pid
sconf="/etc/kerneloops.conf"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

start() {
 	echo -n $"Starting $prog:"
	start_daemon -p $pidfile $exec
	pidof $prog >$pidfile
	retval=$?
	echo
	return $retval
}

stop() {
	echo -n $"Stopping $prog: "
	killproc $prog
	retval=$?
	echo
	return $retval
}

restart() {
	stop
	start
}

reload() {
	restart
}

force_reload() {
	restart
}

fdr_status() {
	status_of_proc $prog
}


case "$1" in
	start|stop|restart|reload)
  		$1
		;;
	force-reload)
		force_reload
		;;
	status)
		fdr_status
		;;
	condrestart|try-restart)
		pidof kerneloops || restart
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|try-restart|reload|force-reload}"
		exit 1
esac

